name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install templ
        run: |
          go get -u github.com/a-h/templ/cmd/templ
          go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate code
        run: templ generate

      - name: Build
        run: go build -v ./...
