name: Go Build and Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'

      - name: Tidy
        run: go mod tidy

      - name: Generate code
        run: |
          go get -u github.com/a-h/templ/cmd/templ@latest
          go install github.com/a-h/templ/cmd/templ@latest
          templ generate

      - name: Build
        run: go build .
        
  cypress-tests:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Clone cypress-example-todomvc
      run: git clone https://github.com/cypress-io/cypress-example-todomvc.git cypress-example-todomvc

    - name: Install Dependencies
      run: |
        cd cypress-example-todomvc
        npm install

    - name: Start Go Application
      run: go run .

    - name: Wait for Go Application to Start
      run: sleep 10 # Adjust this sleep duration based on your app's startup time

    - name: Run Cypress Tests
      run: |
        cd cypress-example-todomvc
        npm run cypress:run

    - name: Stop Go Application
      run: pkill -f "go run ."
  
